### ISSUE TITLE
how do I change the default colors of the signals, neurons and axons?

### ISSUE THREAD

**Issue by Yuki-Taco** [nxxcxx/Neural-Network#3]
Hello!
I've been trying to change the default colors, but nothing changes and the brain is still white on a black background.
Would someone be able to tell me how I can change them, so when the page loads the brain is colored?
Many thanks!!
Helen

**Comment by nxxcxx** [comment]
The default colors are hard coded in these files:
[signals](https://github.com/nxxcxx/Neural-Network/blob/master/js/particlePool.js#L13)
[axons](https://github.com/nxxcxx/Neural-Network/blob/master/js/neuralnet.js#L41)
[neurons](https://github.com/nxxcxx/Neural-Network/blob/master/js/neuralnet.js#L68)
after editing, run `grunt build` command

**Comment by Yuki-Taco** [comment]
Hi,

So sorry to haven’t come back to you before. Thank you so much for your quick response!

Have a great day

Best,
Helen
