### ISSUE TITLE
Generate signal from fix coordinates (not random)

### ISSUE THREAD

**Issue by Nike555** [nxxcxx/Neural-Network#4]
Hi, 
Where in code is possible to change coordinates from generated signal? Because now signal is generated on random coordinates. I would like to make fix coordinates.
Thanks

**Comment by nxxcxx** [comment]
https://github.com/nxxcxx/Neural-Network/blob/b7401b99fe4d318399a525e284244fe33d43ca88/js/neuralnet.js#L250

**Comment by Nike555** [comment]
Thanks.
